// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDneqf4_E2EWWgOkYMXlHutizmG8i3dnOA',
    appId: '1:799549534277:web:35b8250d54c83dee4df32c',
    messagingSenderId: '799549534277',
    projectId: 'form-app-63830',
    authDomain: 'form-app-63830.firebaseapp.com',
    storageBucket: 'form-app-63830.firebasestorage.app',
    measurementId: 'G-KEXV9PXRGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcjVuz1cBAmB0sPgYZsZDZzyW1JOYEnjE',
    appId: '1:799549534277:android:8799ff95e1ebbd114df32c',
    messagingSenderId: '799549534277',
    projectId: 'form-app-63830',
    storageBucket: 'form-app-63830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLZIGlf8_bSMv1ov-z5pzcuIyUoXP7YWE',
    appId: '1:799549534277:ios:a56c19f2bd89dfab4df32c',
    messagingSenderId: '799549534277',
    projectId: 'form-app-63830',
    storageBucket: 'form-app-63830.firebasestorage.app',
    iosBundleId: 'com.example.tradeMark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLZIGlf8_bSMv1ov-z5pzcuIyUoXP7YWE',
    appId: '1:799549534277:ios:a56c19f2bd89dfab4df32c',
    messagingSenderId: '799549534277',
    projectId: 'form-app-63830',
    storageBucket: 'form-app-63830.firebasestorage.app',
    iosBundleId: 'com.example.tradeMark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrxjGmMNKMoT3eAAnlBSUBRlExuhyG8z0',
    appId: '1:799549534277:web:56d98936d0596e134df32c',
    messagingSenderId: '799549534277',
    projectId: 'form-app-63830',
    authDomain: 'form-app-63830.firebaseapp.com',
    storageBucket: 'form-app-63830.firebasestorage.app',
    measurementId: 'G-CTYL79YVRC',
  );
}
